# Generated by Django 3.1.5 on 2021-05-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendsite', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(max_length=100)),
                ('languages', models.CharField(max_length=1000)),
            ],
        ),
    ]
