# Generated by Django 3.1.5 on 2021-05-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendsite', '0005_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repo_href',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
