# Generated by Django 3.1.7 on 2021-12-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendsite', '0006_project_repo_href'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('certificate_id', models.CharField(max_length=1000)),
                ('certificate', models.FileField(upload_to='')),
            ],
        ),
    ]
