# Generated by Django 3.1.7 on 2021-12-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendsite', '0007_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='certificate',
        ),
    ]
