# Generated by Django 3.1.7 on 2021-12-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendsite', '0008_remove_certificate_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_link',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
