# Generated by Django 3.1.7 on 2021-12-15 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendsite', '0010_auto_20211215_2200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cert',
        ),
    ]
