# Generated by Django 3.1.7 on 2021-12-16 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendsite', '0013_auto_20211216_1555'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certification_I',
            new_name='Certification_1',
        ),
        migrations.RenameModel(
            old_name='Certification_II',
            new_name='Certification_2',
        ),
        migrations.RenameModel(
            old_name='Certification_III',
            new_name='Certification_3',
        ),
        migrations.RenameModel(
            old_name='Certification_VI',
            new_name='Certification_4',
        ),
        migrations.RenameModel(
            old_name='Certification_IV',
            new_name='Certification_5',
        ),
        migrations.RenameModel(
            old_name='Certification_KG',
            new_name='Certification_6',
        ),
        migrations.RenameModel(
            old_name='Certification_V',
            new_name='Certification_LKG',
        ),
    ]
