# Generated by Django 3.1.7 on 2022-01-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendsite', '0015_medal_trophy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medal',
            old_name='file',
            new_name='back_side',
        ),
        migrations.AddField(
            model_name='medal',
            name='front_side',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
