# Generated by Django 3.1.7 on 2022-01-18 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendsite', '0016_auto_20220118_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='medal',
            name='STD',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='medal',
            name='organization',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='medal',
            name='name',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
