# Generated by Django 3.1.7 on 2022-01-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendsite', '0017_auto_20220118_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('desc', models.TextField()),
                ('upload', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Certification_1',
        ),
        migrations.DeleteModel(
            name='Certification_2',
        ),
        migrations.DeleteModel(
            name='Certification_3',
        ),
        migrations.DeleteModel(
            name='Certification_4',
        ),
        migrations.DeleteModel(
            name='Certification_5',
        ),
        migrations.DeleteModel(
            name='Certification_6',
        ),
        migrations.DeleteModel(
            name='Certification_LKG',
        ),
        migrations.DeleteModel(
            name='Medal',
        ),
        migrations.DeleteModel(
            name='Trophy',
        ),
    ]
